export const countryFlags: Record<string, string> = {
  'United States': '🇺🇸',
  Denmark: '🇩🇰',
  Finland: '🇫🇮',
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Canada: '🇨🇦',
  Australia: '🇦🇺',
  Ukraine: '🇺🇦',
  China: '🇨🇳',
  Germany: '🇩🇪',
  France: '🇫🇷',
  'United Kingdom': '🇬🇧',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Netherlands: '🇳🇱',
  Switzerland: '🇨🇭',
  Austria: '🇦🇹',
  Belgium: '🇧🇪',
  Italy: '🇮🇹',
  Spain: '🇪🇸',
  Portugal: '🇵🇹',
  Poland: '🇵🇱',
  'Czech Republic': '🇨🇿',
  Hungary: '🇭🇺',
  Romania: '🇷🇴',
  Bulgaria: '🇧🇬',
  Greece: '🇬🇷',
  Turkey: '🇹🇷',
  Russia: '🇷🇺',
  Brazil: '🇧🇷',
  Argentina: '🇦🇷',
  Mexico: '🇲🇽',
  India: '🇮🇳',
  Singapore: '🇸🇬',
  Thailand: '🇹🇭',
  Malaysia: '🇲🇾',
  Indonesia: '🇮🇩',
  Philippines: '🇵🇭',
  Vietnam: '🇻🇳',
  'South Africa': '🇿🇦',
  Egypt: '🇪🇬',
  Israel: '🇮🇱',
  UAE: '🇦🇪',
  'Saudi Arabia': '🇸🇦',
  'New Zealand': '🇳🇿',
  Chile: '🇨🇱',
  Colombia: '🇨🇴',
  Peru: '🇵🇪',
  Ireland: '🇮🇪',
  Iceland: '🇮🇸',
  Luxembourg: '🇱🇺',
  Latvia: '🇱🇻',
  Lithuania: '🇱🇹',
  Estonia: '🇪🇪',
  Slovenia: '🇸🇮',
  Croatia: '🇭🇷',
  Serbia: '🇷🇸',
  'Bosnia and Herzegovina': '🇧🇦',
  Montenegro: '🇲🇪',
  'North Macedonia': '🇲🇰',
  Albania: '🇦🇱',
  Moldova: '🇲🇩',
  Belarus: '🇧🇾',
  Slovakia: '🇸🇰',
};
